[package]
name = "proc-macro-template"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-template-core = { version = "0.1.0", path = "../proc-macro-template-core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"

