[package]
name = "is-odd-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
is-odd-macro-core = { version = "0.1.0", path = "../is-odd-macro-core" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"

